name: Branch name rule
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        uses: actions/github-script@v7
        with:
          script: |
            const name = context.payload.pull_request.head.ref;
            const re = /^(feat|fix|refactor)\/#\d+(-[a-z0-9-]+)?$/;
            if (!re.test(name)) {
              core.setFailed(`브랜치명 규칙 위반: "${name}"
              -> {feat|fix|refactor}/#이슈번호-슬러그 형식이어야 합니다.`);
            }
