# .github/workflows/branch-name.yml
name: Branch name rule
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        uses: actions/github-script@v7
        with:
          script: |
            const name = context.payload.pull_request.head.ref;
            // {아무단어}/#숫자(-옵션슬러그)
            const re = /^[a-zA-Z0-9._-]+\/#\d+(-[a-z0-9-]+)?$/;
            if (!re.test(name)) {
              core.setFailed(
                `브랜치명 규칙 위반: "${name}"\n` +
                `형식: {태그}/#이슈번호-슬러그`
              );
            }
