name: Commit message rule
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch commits in this PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const { data: commits } = await github.request(pr.commits_url, { per_page: 250 });
            const re = /^\[#\d+\];\s*(feat|fix|refactor)(\([^)]+\))?:\s+.+/;
            let bad = [];
            for (const c of commits) {
              const msg = c.commit.message.split('\n')[0]; // 제목만 검사
              if (!re.test(msg)) bad.push(`- ${c.sha.slice(0,7)} "${msg}"`);
            }
            if (bad.length) {
              core.setFailed(
                `커밋 메시지 규칙 위반(첫 줄 형식):\n` +
                `[#이슈번호]; {feat|fix|refactor}(도메인선택): 설명\n\n` +
                bad.join('\n')
              );
            }
