# .github/workflows/pr-title.yml
name: PR title rule
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const re = /^\[#\d+\];\s+.+/;
            if (!re.test(title)) {
              core.setFailed(
                `PR 제목 규칙 위반:\n` +
                `형식: [#이슈번호]; 설명\n` +
                `현재: "${title}"`
              );
            }
